[package]
name = "resolve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.23"
rand = "0.8.5"
trust-dns = "0.22.0"
trust-dns-resolver = "0.22.0"
